[package]
name = "advent2022"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pathfinding = "4.0"
jemallocator = "0.5.0"

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
